In [30]:
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import load_model
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from sklearn.preprocessing import MinMaxScaler

In [5]:
df = pd.read_csv('data_asia.csv')

In [43]:
# Select relevant features and target
features = df[['School enrollment, primary', 'School enrollment, tertiary']]
target = df[['Primary completion rate', 'Literacy rate']]



In [56]:
scaler_features = MinMaxScaler()
scaler_targets = MinMaxScaler()

features_scaled = scaler_features.fit_transform(features)
targets_scaled = scaler_targets.fit_transform(target)


In [61]:
# Split data into training, validation, and testing sets
X_train, X_test, y_train, y_test = train_test_split(features_scaled, targets_scaled, test_size=0.2, random_state=42)

X_train = X_train.reshape(X_train.shape[0], 1, X_train.shape[1])
X_test = X_test.reshape(X_test.shape[0], 1, X_test.shape[1])


[[[0.58842014 0.21671132]]

 [[0.63683672 0.13792124]]

 [[       nan 0.24767337]]

 ...

 [[0.48156264        nan]]

 [[0.55251949        nan]]

 [[0.65523494 0.39527546]]] [[[0.69307676 0.11332482]]

 [[       nan        nan]]

 [[0.67759809 0.57274289]]

 [[0.68955742 0.31268412]]

 [[0.66984253 0.10234607]]

 [[0.6109772         nan]]

 [[0.66339359 0.280865  ]]

 [[       nan        nan]]

 [[0.59431857        nan]]

 [[0.57546179 0.60266108]]

 [[0.63985804 0.45537042]]

 [[       nan        nan]]

 [[0.58873647        nan]]

 [[0.6666588  0.14831142]]

 [[0.69429868 0.03214561]]

 [[       nan        nan]]

 [[0.58568308 0.23078507]]

 [[0.57581108 0.33133037]]

 [[0.65869161 0.20127536]]

 [[0.5713383  0.41666356]]

 [[0.67478407 0.30179695]]

 [[0.58541049        nan]]

 [[0.78345984 0.27324362]]

 [[0.59119804 0.14867876]]

 [[0.48251525 0.07634641]]

 [[       nan        nan]]

 [[0.59777221 0.61433619]]

 [[       nan        nan]]

 [[0.62019095 0.29283204]]

 [[       nan 

In [59]:
model = tf.keras.models.Sequential([
    tf.keras.layers.SimpleRNN(50, activation='relu', input_shape=(X_train.shape[1], X_train.shape[2])),
    tf.keras.layers.Dense(2)  # 2 đầu ra cho 2 cột cần dự đoán
])

model.compile(optimizer='adam', loss='mean_squared_error')

In [60]:
model.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_test, y_test), verbose=1)


Epoch 1/50
33/33 [==============================] - 1s 9ms/step - loss: nan - val_loss: nan
Epoch 2/50
33/33 [==============================] - 0s 2ms/step - loss: nan - val_loss: nan
Epoch 3/50
33/33 [==============================] - 0s 2ms/step - loss: nan - val_loss: nan
Epoch 4/50
33/33 [==============================] - 0s 2ms/step - loss: nan - val_loss: nan
Epoch 5/50
33/33 [==============================] - 0s 2ms/step - loss: nan - val_loss: nan
Epoch 6/50
33/33 [==============================] - 0s 2ms/step - loss: nan - val_loss: nan
Epoch 7/50
33/33 [==============================] - 0s 2ms/step - loss: nan - val_loss: nan
Epoch 8/50
33/33 [==============================] - 0s 2ms/step - loss: nan - val_loss: nan
Epoch 9/50
33/33 [==============================] - 0s 2ms/step - loss: nan - val_loss: nan
Epoch 10/50
33/33 [==============================] - 0s 2ms/step - loss: nan - val_loss: nan
Epoch 11/50
33/33 [==============================] - 0s 2ms/step - loss: nan - 

In [62]:
predicted_values_scaled = model.predict(X_test)


9/9 [==============================] - 0s 997us/step


In [63]:
predicted_values = scaler_targets.inverse_transform(predicted_values_scaled)
